#!/usr/bin/env bash
set -euo pipefail

# Colors via printf (portable — echo -e is not POSIX)
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

printf "${BLUE}"
printf "  ____      _         _ _ \n"
printf " |  _ \\ ___| | ____ _| | |\n"
printf " | |_) / _ \\ |/ / _\` | | |\n"
printf " |  _ <  __/   < (_| | | |\n"
printf " |_| \\_\\___|_|\\_\\__,_|_|_|\n"
printf "\n"
printf " A second brain that builds itself.\n"
printf "${NC}\n"

# --- Preflight checks ---

# Check for Python 3
PYTHON=""
for cmd in python3 python; do
  if command -v "$cmd" > /dev/null 2>&1; then
    if "$cmd" -c 'import sys; sys.exit(0 if sys.version_info[0] >= 3 else 1)' 2>/dev/null; then
      PYTHON="$cmd"
      break
    fi
  fi
done

if [ -z "$PYTHON" ]; then
  printf "${RED}Error: Python 3 is required but not found.${NC}\n"
  printf "Install from https://python.org or via your package manager.\n"
  exit 1
fi

# Check for Node.js/npx (needed for MCP server)
HAS_NPX=true
if ! command -v npx > /dev/null 2>&1; then
  HAS_NPX=false
fi

# --- Step 1: Get user name ---
printf "${GREEN}What's your name?${NC} "
read -r USER_NAME
if [ -z "$USER_NAME" ]; then
  printf "Name is required.\n"
  exit 1
fi

# --- Step 2: Get vault path ---
DEFAULT_VAULT="$HOME/Obsidian Vault"
printf "${GREEN}Where should your vault live?${NC} (default: %s) " "$DEFAULT_VAULT"
read -r VAULT_PATH
VAULT_PATH="${VAULT_PATH:-$DEFAULT_VAULT}"

# Expand ~ if present
VAULT_PATH="${VAULT_PATH/#\~/$HOME}"

printf "\n"
printf "${BLUE}Setting up Rekall for %s at %s${NC}\n" "$USER_NAME" "$VAULT_PATH"
printf "\n"

# --- Portable sed-in-place (temp file + mv, works on BSD and GNU) ---
sed_inplace() {
  local file="$1"
  shift
  local tmpfile
  tmpfile="$(mktemp)" || return 1
  sed "$@" "$file" > "$tmpfile" && mv "$tmpfile" "$file"
}

# --- Step 3: Create vault from template ---
printf "${YELLOW}[1/7] Creating vault...${NC}\n"
for dir in Projects Research Decisions Ideas Sessions; do
  mkdir -p "$VAULT_PATH/$dir"
done

# Copy template files (don't overwrite existing)
for file in Home.md AGENDA.md; do
  if [ ! -f "$VAULT_PATH/$file" ]; then
    sed "s/{{DATE}}/$(date +%Y-%m-%d)/g" "$SCRIPT_DIR/vault/$file" > "$VAULT_PATH/$file"
  fi
done

# Create About file
ABOUT_FILE="$VAULT_PATH/About ${USER_NAME}.md"
if [ ! -f "$ABOUT_FILE" ]; then
  cat > "$ABOUT_FILE" << EOF
---
date: $(date +%Y-%m-%d)
tags: [reference]
status: active
summary: "Profile and preferences for ${USER_NAME}"
---

# About ${USER_NAME}

## Role & Background
_What do you do? What's your expertise?_

## Preferences
_How do you like to work? What matters to you?_

## Working Style
_Communication preferences, tools, habits._
EOF
fi

# --- Step 4: Copy hooks ---
printf "${YELLOW}[2/7] Installing hooks...${NC}\n"
mkdir -p "$HOME/.claude/hooks"
for hook in session-logger.py compile-memory.sh vault-lint.sh secrets-check.sh dangerous-cmd-check.sh file-size-check.sh; do
  cp "$SCRIPT_DIR/hooks/$hook" "$HOME/.claude/hooks/$hook"
done
chmod +x "$HOME/.claude/hooks/"*.sh "$HOME/.claude/hooks/"*.py

# --- Step 5: Write config file (sourced by all hooks) ---
printf "${YELLOW}[3/7] Writing config...${NC}\n"
CONFIG_DIR="$HOME/.claude"
CONFIG_FILE="$CONFIG_DIR/rekall.conf"
cat > "$CONFIG_FILE" << EOF
# Generated by Rekall setup on $(date +%Y-%m-%d)
REKALL_VAULT_PATH="$VAULT_PATH"
REKALL_USER_NAME="$USER_NAME"
REKALL_PYTHON="$PYTHON"
EOF

# --- Step 6: Copy commands ---
printf "${YELLOW}[4/7] Installing commands...${NC}\n"
mkdir -p "$HOME/.claude/commands"
for cmd in "$SCRIPT_DIR/commands/"*.md; do
  cp "$cmd" "$HOME/.claude/commands/"
done

# --- Step 7: Set up memory ---
printf "${YELLOW}[5/7] Setting up memory system...${NC}\n"
# Use a stable, CWD-independent memory directory
MEMORY_DIR="$HOME/.claude/rekall/memory"
mkdir -p "$MEMORY_DIR"
if [ ! -f "$MEMORY_DIR/instincts.jsonl" ]; then
  cp "$SCRIPT_DIR/memory/instincts.jsonl" "$MEMORY_DIR/"
fi
if [ ! -f "$MEMORY_DIR/MEMORY.md" ]; then
  cp "$SCRIPT_DIR/memory/MEMORY.md" "$MEMORY_DIR/"
fi

# Also write memory dir to config
cat >> "$CONFIG_FILE" << EOF
REKALL_MEMORY_DIR="$MEMORY_DIR"
EOF

# --- Step 8: Patch CLAUDE.md ---
printf "${YELLOW}[6/7] Configuring CLAUDE.md...${NC}\n"
CLAUDE_MD="$HOME/.claude/CLAUDE.md"
REKALL_SECTION="$SCRIPT_DIR/CLAUDE.md"

# Use temp file to patch placeholders (portable — no sed -i)
PATCHED_FILE="$(mktemp)"
sed "s|{{VAULT_PATH}}|$VAULT_PATH|g; s|{{USER_NAME}}|$USER_NAME|g; s|{{MEMORY_DIR}}|$MEMORY_DIR|g; s|{{DATE}}|$(date +%Y-%m-%d)|g" "$REKALL_SECTION" > "$PATCHED_FILE"
PATCHED=$(cat "$PATCHED_FILE")
rm -f "$PATCHED_FILE"

if [ -f "$CLAUDE_MD" ]; then
  if grep -q "Rekall" "$CLAUDE_MD"; then
    printf "  CLAUDE.md already has Rekall config — skipping (delete the Rekall section to regenerate)\n"
  else
    printf "\n%s\n" "$PATCHED" >> "$CLAUDE_MD"
  fi
else
  printf "%s\n" "$PATCHED" > "$CLAUDE_MD"
fi

# --- Step 9: Merge settings.json ---
printf "${YELLOW}[7/7] Configuring settings.json and MCP...${NC}\n"

export _REKALL_VAULT="$VAULT_PATH"

"$PYTHON" << 'PYEOF'
import json
import os
import sys

settings_path = os.path.expanduser("~/.claude/settings.json")
vault_path = os.environ.get("_REKALL_VAULT", "")

if os.path.exists(settings_path):
    with open(settings_path, encoding="utf-8") as f:
        settings = json.load(f)
else:
    settings = {}

# Vault permissions
settings.setdefault("permissions", {}).setdefault("allow", [])
vault_perms = [
    f"Read({vault_path}/**)",
    f"Edit({vault_path}/**)",
    f"Write({vault_path}/**)",
    f"Glob({vault_path}/**)",
    f"Grep({vault_path}/**)",
]
for perm in vault_perms:
    if perm not in settings["permissions"]["allow"]:
        settings["permissions"]["allow"].append(perm)

# Hooks
settings.setdefault("hooks", {})

# PreToolUse hooks
settings["hooks"].setdefault("PreToolUse", [])
pre_hooks = {
    "Write|Edit": 'bash "$HOME/.claude/hooks/secrets-check.sh"',
    "Bash": 'bash "$HOME/.claude/hooks/dangerous-cmd-check.sh"',
}
for matcher, cmd in pre_hooks.items():
    exists = any(
        h.get("matcher") == matcher and
        any(hh.get("command") == cmd for hh in h.get("hooks", []))
        for h in settings["hooks"]["PreToolUse"]
    )
    if not exists:
        settings["hooks"]["PreToolUse"].append({
            "matcher": matcher,
            "hooks": [{"type": "command", "command": cmd, "timeout": 10}]
        })

# PostToolUse hooks
settings["hooks"].setdefault("PostToolUse", [])
post_hooks = [
    ("Write|Edit", 'bash "$HOME/.claude/hooks/file-size-check.sh"'),
    ("Write|Edit", 'bash "$HOME/.claude/hooks/vault-lint.sh"'),
]
for matcher, cmd in post_hooks:
    exists = any(
        h.get("matcher") == matcher and
        any(hh.get("command") == cmd for hh in h.get("hooks", []))
        for h in settings["hooks"]["PostToolUse"]
    )
    if not exists:
        settings["hooks"]["PostToolUse"].append({
            "matcher": matcher,
            "hooks": [{"type": "command", "command": cmd, "timeout": 10}]
        })

# SessionStart hook (increased timeout for first-run processing)
settings["hooks"].setdefault("SessionStart", [])
session_cmd = 'bash "$HOME/.claude/hooks/compile-memory.sh"'
exists = any(
    any(hh.get("command") == session_cmd for hh in h.get("hooks", []))
    for h in settings["hooks"]["SessionStart"]
)
if not exists:
    settings["hooks"]["SessionStart"].append({
        "matcher": "startup|resume",
        "hooks": [{"type": "command", "command": session_cmd, "timeout": 30}]
    })

with open(settings_path, "w", encoding="utf-8") as f:
    json.dump(settings, f, indent=2)

print("  Settings merged successfully")
PYEOF

# --- MCP config ---
if [ "$HAS_NPX" = true ]; then
  _REKALL_VAULT="$VAULT_PATH" "$PYTHON" << 'PYEOF'
import json
import os

mcp_path = os.path.expanduser("~/.claude/mcp.json")
vault_path = os.environ.get("_REKALL_VAULT", "")

if os.path.exists(mcp_path):
    with open(mcp_path, encoding="utf-8") as f:
        mcp = json.load(f)
else:
    mcp = {}

mcp.setdefault("mcpServers", {})

if "obsidian" not in mcp["mcpServers"]:
    mcp["mcpServers"]["obsidian"] = {
        "command": "npx",
        "args": ["-y", "@bitbonsai/mcpvault@latest", vault_path]
    }
    print("  MCP obsidian server configured")
else:
    print("  MCP obsidian server already configured — skipping")

with open(mcp_path, "w", encoding="utf-8") as f:
    json.dump(mcp, f, indent=2)
PYEOF
else
  printf "  ${YELLOW}Skipping MCP config — npx not found. Install Node.js to enable the Obsidian MCP server.${NC}\n"
fi

# Copy project mappings example
if [ ! -f "$HOME/.claude/rekall-projects.json" ]; then
  cp "$SCRIPT_DIR/rekall-projects.json.example" "$HOME/.claude/rekall-projects.json"
fi

printf "\n"
printf "${GREEN}Done! Rekall installed.${NC}\n"
printf "\n"
printf "  Vault:    %s\n" "$VAULT_PATH"
printf "  About:    About %s.md\n" "$USER_NAME"
printf "  Config:   %s\n" "$CONFIG_FILE"
printf "  Hooks:    ~/.claude/hooks/ (6 hooks)\n"
printf "  Commands: ~/.claude/commands/ (4 commands)\n"
printf "  Memory:   %s\n" "$MEMORY_DIR"
printf "\n"
printf "${BLUE}Start a new Claude Code session — your past conversations will be processed automatically.${NC}\n"
printf "\n"
printf "  Commands available:\n"
printf "    /session-log          — capture current session\n"
printf "    /vault-health         — audit vault health\n"
printf "    /vault-consolidate    — synthesize project knowledge\n"
printf "    /instincts-review     — review memory system\n"
